### ISSUE TITLE
Latency issues

### ISSUE THREAD

**Issue by nturton256** [stassara/CodeIgniter-GeoIP-Library#1]
I am using this and I find that the loading times increase dramatically (taking on average 2.7 seconds).  Is there any way of improving the latency of it?

**Comment by stassara** [comment]
Hi, the library is not the problem.

![captura de pantalla 2016-09-20 a las 11 18 55 a m](https://cloud.githubusercontent.com/assets/5396721/18673964/0f8890d8-7f24-11e6-80ed-d7fe13f028a8.png)

![captura de pantalla 2016-09-20 a las 11 15 33 a m](https://cloud.githubusercontent.com/assets/5396721/18673836/9dc3efe2-7f23-11e6-8b5e-23546b8966a2.png)

Hope speed will come soon :)
